version: "3.8"
   
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    networks:
      - default

  db:
    image: postgres
    env_file:
      - .env.db
    volumes:
      - "./data/postgres:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
      - default
    
  postgres-ui:
    image: dpage/pgadmin4
    env_file:
      - .env.pg
    container_name: pgadmin-web
    ports:
      - "5050:80"
    depends_on:
      - db
    links:
      - db
    networks:
      - default
