version: "3.8"
   
services:
  api:
    build: .
    command: npm run start
    container_name: tsdc-vynils-api
    volumes:
      - /usr/src/app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    networks:
      - default

  db:
    image: postgres
    container_name: postgres-db
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    networks:
      - default
